name: Auto release on bot merge
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Create release
    if:
      github.event.head_commit.author.name == 'vivodi'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.token }}
